version: '3.8'
services:
  devcontainer:
    container_name: sembackend-devcontainer-1
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/sem_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=sem_service
      - FLYWAY_URL=jdbc:mysql://db:3306/sem_db
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=sem_service
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sem_service
      - MYSQL_DATABASE=sem_db
    ports:
      - "3306:3306"

volumes:
  mysql-data:
