version: '3.8'
services:
  devcontainer:
    container_name: sembackend-devcontainer-1
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/sem_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=sem_service
      - FLYWAY_URL=jdbc:mysql://db:3306/sem_db
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=sem_service
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sem_service
      - MYSQL_DATABASE=sem_db
    ports:
      - "3306:3306"
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

volumes:
  mysql-data:
