@startuml
actor User as "Người Dùng"
boundary Server as "Server"
entity NoSQL as "Cơ Sở Dữ Liệu NoSQL"
control KafkaProducer as "Kafka Producer"
control SparkStreaming as "Spark Streaming"
entity DataLake as "DataLake"

User -> Server : Tải tệp lên
Server -> Server : Parse tệp và lưu metadata
Server -> NoSQL : Lưu metadata của tệp

Server -> KafkaProducer : Gửi dữ liệu gốc (File Gốc) vào Kafka Topic 1
Server -> KafkaProducer : Gửi dữ liệu parse vào Kafka Topic 2

KafkaProducer -> Kafka : Lưu trữ dữ liệu vào Topic 1 và Topic 2

Kafka -> SparkStreaming : Spark Streaming nhận dữ liệu từ Topic 1 (Dữ liệu gốc)
Kafka -> SparkStreaming : Spark Streaming nhận dữ liệu từ Topic 2 (Dữ liệu parse)

SparkStreaming -> SparkStreaming : Xử lý dữ liệu gốc
SparkStreaming -> SparkStreaming : Xử lý dữ liệu parse
SparkStreaming -> DataLake : Lưu trữ dữ liệu vào DataLake

@enduml
