CREATE TABLE equipment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    equipment_name VARCHAR(255) NOT NULL UNIQUE,
    category ENUM('TEACHING_EQUIPMENT', 'LABORATORY_EQUIPMENT', 'OFFICE_EQUIPMENT', 'SPORTS_EQUIPMENT', 'INFORMATION_TECHNOLOGY_EQUIPMENT', 'ELECTRONIC_EQUIPMENT'),
    totalQuantity INT NOT NULL,
    usableQuantity INT NOT NULL,
    brokenQuantity INT NOT NULL,
);