CREATE TABLE room (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_name VARCHAR(255) NOT NULL UNIQUE,
    type ENUM('CLASSROOM', 'LABORATORY', 'EQUIPMENT_ROOM', 'MEETING_ROOM', 'OFFICE') DEFAULT 'CLASSROOM',
    status ENUM('AVAILABLE', 'OCCUPIED', 'BROKEN') DEFAULT 'AVAILABLE',
    capacity INT NOT NULL
);
