### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/api/v1/equipment/sorted-by-room

###

GET http://localhost:8080/api/v1/room/available?type=phòng%20thí%20nghiệm&date=2024-10-21&period=tiết%203

###

GET http://localhost:8080/api/v1/room/search?capacity=30&comparisonOperator=%3E&roomCondition=in_use

###

GET http://localhost:8080/api/v1/user/2

###

POST http://localhost:8080/api/v1/user/new
Content-Type: application/json

{
"username": "sbm-user"
}

###

PATCH http://localhost:8080/api/v1/user/update/4
Content-Type: application/json

{
  "password": "Azure-user*2312"
}