//checked
GET http://localhost:8080/api/v1/equipment/sorted-by-room

###

GET http://localhost:8080/api/v1/room/available?type=laboratory&date=2024-10-21&period=tiết%203

###

GET http://localhost:8080/api/v1/room/search?capacity=30&comparisonOperator=%3E&status=in_use

###

GET http://localhost:8080/api/v1/user/5

###

POST http://localhost:8080/api/v1/user/new
Content-Type: application/json

{
"username": "sbm-user"
}

###

PATCH http://localhost:8080/api/v1/user/update/4
Content-Type: application/json

{
  "password": "Azure-user*2312"
}

###

GET http://localhost:8080/api/v1/room/filter

###

POST http://localhost:8080/api/v1/borrow/room
Content-Type: application/json

{
  "userId": 2,
  "roomId": 2,
  "startTime": "2024-11-12T09:00:00",
  "endTime": "2024-11-12T11:00:00",
  "comment": "lớp thí nghiệm lý"
}

###

PATCH http://localhost:8080/api/v1/borrow/room/partialUpdate
Content-Type: application/json

{
  "uniqueId": 1,
  "userId": 1,
  "startTime": "2024-11-15T10:00:00",
  "endTime": "2024-11-15T12:00:00"
}
